"""
Apply Memory Kernel to L=6 Monte Carlo Data
UDCT v2.6.7 - Higgs Hierarchy Stabilization

This script loads plaquette time series from L=6 Monte Carlo simulation
and applies the Adaptive Memory Kernel to demonstrate stabilization effects.
"""

import numpy as np
import matplotlib.pyplot as plt
from memory_kernel import MemoryKernel


def main():
    # Load plaquette time series generated by u1_monte_carlo_L6.py
    try:
        plaquette_series = np.load("plaquette_series_L6_beta1.0.npy")
    except FileNotFoundError:
        print("Error: plaquette_series_L6_beta1.0.npy not found.")
        print("Please run u1_monte_carlo_L6.py first to generate the data.")
        return

    print(f"Loaded {len(plaquette_series)} plaquette measurements from L=6 simulation.")
    print(f"Raw Mean: {np.mean(plaquette_series):.6f}")
    print(f"Raw Std : {np.std(plaquette_series):.6f}")

    # Initialize Memory Kernel (using good parameters from v2.6.6)
    kernel = MemoryKernel(
        memory_length=20,
        decay_factor=0.85,
        outlier_threshold=0.008,
        large_diff_threshold=0.007,
        min_large_diff_threshold=0.0025,
        adaptive_threshold_factor=2.8,
        phase_jump_adaptation_steps=8
    )

    # Apply Memory Kernel
    smoothed_series = []
    for value in plaquette_series:
        smoothed = kernel.apply(value)
        smoothed_series.append(smoothed)

    smoothed_series = np.array(smoothed_series)

    print(f"\nSmoothed Mean: {np.mean(smoothed_series):.6f}")
    print(f"Smoothed Std : {np.std(smoothed_series):.6f}")
    print(f"Std Reduction: {(1 - np.std(smoothed_series)/np.std(plaquette_series))*100:.2f}%")

    # Create comparison plots
    fig, axes = plt.subplots(2, 1, figsize=(12, 8))

    # Time series plot
    axes[0].plot(plaquette_series, label="Raw Plaquette", alpha=0.6, color="gray")
    axes[0].plot(smoothed_series, label="Smoothed (Memory Kernel)", linewidth=2, color="blue")
    axes[0].set_xlabel("Measurement Step")
    axes[0].set_ylabel("Plaquette Value")
    axes[0].set_title("L=6 Monte Carlo: Raw vs Memory Kernel Smoothed Plaquette")
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Histogram comparison
    axes[1].hist(plaquette_series, bins=40, alpha=0.5, label="Raw", color="gray", density=True)
    axes[1].hist(smoothed_series, bins=40, alpha=0.7, label="Smoothed", color="blue", density=True)
    axes[1].set_xlabel("Plaquette Value")
    axes[1].set_ylabel("Density")
    axes[1].set_title("Distribution Comparison")
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig("../figures/memory_kernel_L6_comparison.png", dpi=150)
    print("\nPlot saved to ../figures/memory_kernel_L6_comparison.png")

    # Optional: Save smoothed data
    np.save("smoothed_plaquette_L6.npy", smoothed_series)
    print("Smoothed data saved to smoothed_plaquette_L6.npy")


if __name__ == "__main__":
    main()
